# Generated by Django 2.1.5 on 2019-01-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbName', models.CharField(max_length=100)),
                ('dbUsername', models.CharField(max_length=100)),
                ('dbPassword', models.CharField(max_length=100)),
                ('dbHost', models.CharField(max_length=100)),
                ('dbPort', models.IntegerField(max_length=100)),
            ],
        ),
    ]
