# Generated by Django 2.1.5 on 2019-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnames',
            name='dbPort',
            field=models.IntegerField(),
        ),
    ]
